spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
