spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${RAILWAY_DB_HOST}:${RAILWAY_DB_PORT}/${RAILWAY_DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${RAILWAY_DB_USERNAME}
    password: ${RAILWAY_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
