spring:
  application:
    name: class-service
  datasource:
    url: jdbc:mysql://${RAILWAY_DB_HOST}:${RAILWAY_DB_PORT}/${RAILWAY_DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${RAILWAY_DB_USERNAME}
    password: ${RAILWAY_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate: { ddl-auto: update }
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8084
