server:
  port: 8080

jwt:
  secret: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: clients
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/clients/**, /api/v1/goals/**, /api/v1/measurements/**
        - id: plan-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/plans/**
        - id: class-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/classes/**
        - id: admin-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/trainers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: ERROR
    org:
      springframework: DEBUG
      springframework.cloud: DEBUG
      springframework.web: DEBUG
      springframework.security: DEBUG
      springframework.cloud.gateway: DEBUG

