server:
  port: 8800

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: plan-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/plans/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: ERROR
    org:
      springframework: DEBUG
      springframework.cloud: DEBUG
      springframework.web: DEBUG
      springframework.security: DEBUG
      springframework.cloud.gateway: DEBUG

