spring:
  application:
    name: plan-service
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
